// Set to false before shipping — this bypasses all Supabase calls
export const USE_MOCK = false;

const today = new Date();
function daysFromToday(n: number) {
  const d = new Date(today);
  d.setDate(today.getDate() + n);
  return d.toISOString().split("T")[0];
}

export const MOCK_PROFILE = {
  id: "mock-tutor-id",
  full_name: "Jordan Lee",
  role: "parent" as const,
  email: "jordan@studywiser.dev",
  phone: null,
  dob: null,
  avatar_url: null,
};

export const MOCK_PARENT_PROFILE = {
  id: "mock-parent-id",
  full_name: "Sarah Williams",
  role: "parent" as const,
  email: "sarah@studywiser.dev",
};

// ── Tutor profile screen data (subjects / availability / stats) ──────────────
// Times are 12-hour with AM/PM so the profile reads naturally.
export const MOCK_TUTOR_PROFILE = {
  subjects: [
    "SAT Math",
    "SAT Reading & Writing",
    "Algebra I / II",
    "Pre-Calculus / Calculus",
    "Biology",
  ],
  // Stored in 24-hour (like the DB); the UI formats to 12-hour AM/PM for display.
  availability: {
    Mon: { start: "15:00", end: "19:00" },
    Wed: { start: "15:00", end: "19:00" },
    Thu: { start: "16:00", end: "20:00" },
    Sat: { start: "10:00", end: "14:00" },
  } as Record<string, { start: string; end: string }>,
  stats: { sessions: 128, students: 24 },
};

// ── Sessions for the TUTOR schedule screen ──────────────────────────────────
export const MOCK_TUTOR_SESSIONS = [
  {
    id: "ts1",
    session_date: daysFromToday(0),
    session_time: "10:00:00",
    duration: 60,
    subject: "SAT Math",
    status: "upcoming" as const,
    format: "Virtual",
    frequency: "Weekly",
    price: 45,
    student_name: "Liam Williams",
    meeting_url: "https://meet.google.com/abc-defg-hij",
  },
  {
    id: "ts2",
    session_date: daysFromToday(0),
    session_time: "16:00:00",
    duration: 60,
    subject: "Pre-Calculus / Calculus",
    status: "pending" as const,
    format: "In-Person",
    frequency: "Biweekly",
    price: 40,
    student_name: "Marcus Thompson",
    meeting_url: null,
  },
  {
    id: "ts3",
    session_date: daysFromToday(1),
    session_time: "14:00:00",
    duration: 90,
    subject: "Algebra I / II",
    status: "upcoming" as const,
    format: "Virtual",
    frequency: "Weekly",
    price: 60,
    student_name: "Emma Chen",
    meeting_url: null,
  },
  {
    id: "ts4",
    session_date: daysFromToday(2),
    session_time: "11:00:00",
    duration: 60,
    subject: "SAT Reading & Writing",
    status: "upcoming" as const,
    format: "Virtual",
    frequency: "Weekly",
    price: 45,
    student_name: "Aisha Patel",
    meeting_url: "https://meet.google.com/xyz-uvwx-yz1",
  },
  {
    id: "ts5",
    session_date: daysFromToday(-1),
    session_time: "11:00:00",
    duration: 60,
    subject: "SAT Reading & Writing",
    status: "completed" as const,
    format: "Virtual",
    frequency: "Weekly",
    price: 45,
    student_name: "Liam Williams",
    meeting_url: null,
  },
  {
    id: "ts6",
    session_date: daysFromToday(-3),
    session_time: "09:00:00",
    duration: 90,
    subject: "Algebra I / II",
    status: "completed" as const,
    format: "Virtual",
    frequency: "Weekly",
    price: 60,
    student_name: "Emma Chen",
    meeting_url: null,
  },
];

// ── Sessions for the PARENT sessions screen ──────────────────────────────────
export const MOCK_PARENT_SESSIONS = [
  {
    id: "ps1",
    student_name: "Liam Williams",
    subject: "SAT Math",
    tutor_name: "Jordan Lee",
    session_date: daysFromToday(0),
    session_time: "10:00:00",
    duration: 60,
    format: "Virtual",
    frequency: "Weekly",
    price: 45,
    status: "upcoming" as const,
    meeting_url: "https://meet.google.com/abc-defg-hij",
  },
  {
    id: "ps2",
    student_name: "Liam Williams",
    subject: "Chemistry",
    tutor_name: "Jordan Lee",
    session_date: daysFromToday(0),
    session_time: "14:00:00",
    duration: 60,
    format: "In-Person",
    frequency: "Weekly",
    price: 40,
    status: "pending" as const,
    meeting_url: null,
  },
  {
    id: "ps3",
    student_name: "Emma Williams",
    subject: "Biology",
    tutor_name: "Jordan Lee",
    session_date: daysFromToday(2),
    session_time: "15:00:00",
    duration: 60,
    format: "Virtual",
    frequency: "Biweekly",
    price: 40,
    status: "upcoming" as const,
    meeting_url: null,
  },
  {
    id: "ps4",
    student_name: "Liam Williams",
    subject: "SAT Math",
    tutor_name: "Jordan Lee",
    session_date: daysFromToday(-1),
    session_time: "10:00:00",
    duration: 60,
    format: "Virtual",
    frequency: "Weekly",
    price: 45,
    status: "completed" as const,
    meeting_url: null,
  },
  {
    id: "ps5",
    student_name: "Emma Williams",
    subject: "Biology",
    tutor_name: "Jordan Lee",
    session_date: daysFromToday(-4),
    session_time: "15:00:00",
    duration: 60,
    format: "Virtual",
    frequency: "Biweekly",
    price: 40,
    status: "completed" as const,
    meeting_url: null,
  },
];

// ── Session notes (keyed by session ID) ──────────────────────────────────────
export const MOCK_SESSION_NOTES: Record<string, string> = {
  ts5: "Great focus today! Here's what we covered:\n\n• Paired passage strategy — annotate as you read, don't re-read\n• Evidence questions: eliminate the 2-wrong-answer trap\n• Timed practice: 2 full reading sections (score improved ~50 pts on practice)\n\nHomework:\nComplete one Khan Academy reading section. Focus on annotation, not re-reading.\n\nNext session:\nMove into Writing & Language — sentence structure and transitions.",
  ps4: "Liam did great today! Summary:\n\n• Grid-in problems: worked through 15 problems, got 12 correct\n• Reviewed linear equations and systems of equations\n• Key weakness identified: reading the question carefully before solving\n\nHomework:\nPractice 20 grid-in problems from the College Board blue book (p. 214–216).\n\nNext session:\nStart data analysis section. Algebra is strong — data will be a quick win.",
};

// ── Session requests for the TUTOR find screen ───────────────────────────────
export const MOCK_SESSION_REQUESTS = [
  {
    id: "req1",
    student_name: "Aiden Park",
    student_profile_id: null,
    student_id: null,
    parent_id: "fake-parent-1",
    subject: "SAT Math",
    grade: "10th Grade",
    session_type: "Individual",
    format: "Virtual",
    frequency: "Weekly",
    sessions_per_period: 1,
    preferred_date: daysFromToday(3),
    preferred_time: "16:00:00",
    duration: 60,
    zip: null,
    notes: "Struggling with grid-in problems and time management. Test is in October.",
  },
  {
    id: "req2",
    student_name: "Sofia Martinez",
    student_profile_id: null,
    student_id: null,
    parent_id: "fake-parent-2",
    subject: "Algebra I / II",
    grade: "8th Grade",
    session_type: "Individual",
    format: "Virtual",
    frequency: "Biweekly",
    sessions_per_period: 1,
    preferred_date: daysFromToday(5),
    preferred_time: "17:00:00",
    duration: 90,
    zip: null,
    notes: "Looking for a patient tutor who can explain things from scratch. Learns best with visual examples.",
  },
  {
    id: "req3",
    student_name: "Noah Kim",
    student_profile_id: null,
    student_id: null,
    parent_id: "fake-parent-3",
    subject: "Biology",
    grade: "11th Grade",
    session_type: "Individual",
    format: "In-Person",
    frequency: "Weekly",
    sessions_per_period: 1,
    preferred_date: daysFromToday(2),
    preferred_time: "15:00:00",
    duration: 60,
    zip: "02134",
    notes: "Preparing for AP Bio in May. Strong in ecology, needs help with cell biology and genetics.",
  },
  {
    id: "req4",
    student_name: "Isabella Torres",
    student_profile_id: null,
    student_id: null,
    parent_id: "fake-parent-4",
    subject: "Chemistry",
    grade: "10th Grade",
    session_type: "Individual",
    format: "In-Person",
    frequency: "Weekly",
    sessions_per_period: 2,
    preferred_date: daysFromToday(1),
    preferred_time: "14:00:00",
    duration: 60,
    zip: "02215",
    notes: null,
  },
  {
    id: "req5",
    student_name: "Ethan Johnson",
    student_profile_id: null,
    student_id: null,
    parent_id: "fake-parent-5",
    subject: "Pre-Calculus / Calculus",
    grade: "11th Grade",
    session_type: "Individual",
    format: "Virtual",
    frequency: "Biweekly",
    sessions_per_period: 1,
    preferred_date: daysFromToday(6),
    preferred_time: "18:00:00",
    duration: 60,
    zip: null,
    notes: "Starting calculus next semester, wants to get ahead over the summer.",
  },
];

// ── Students for PARENT home ──────────────────────────────────────────────────
export const MOCK_STUDENTS = [
  { id: "stu1", full_name: "Liam Williams",  grade_level: "8th Grade",  profile_id: null, link_code: "AB12CD" },
  { id: "stu2", full_name: "Emma Williams",  grade_level: "10th Grade", profile_id: "stu2-profile", link_code: "XY34ZW" },
];
